nih14:
  images_path: "/path/to/nih14/images"
  train_list: "Xray14_train_official.txt"
  disease_embedding_path: "/path/to/nih14/embeddings"
  img_extension: ""
  input_type: "global"

shenzhen:
  images_path: "/path/to/shenzhen/images"
  train_list: "ShenzenCXR_train_data.txt"
  disease_embedding_path: "/path/to/shenzhen/embeddings"
  img_extension: ""
  input_type: "global"

chexpert:
  images_path: "/path/to/chexpert/images"
  train_list: "CheXpert_train_val.csv"
  disease_embedding_path: "/path/to/chexpert/embeddings"
  img_extension: ""
  input_type: "global"

padchest:
  images_path: "/path/to/padchest/images"
  train_list: "padchest_train.txt"
  disease_embedding_path: "/path/to/padchest/embeddings"
  img_extension: ""
  input_type: "global"

vindrcxr:
  images_path: "/path/to/vindrcxr/images"
  train_list: "VinDrCXR_train_pe_global_one.txt"
  disease_embedding_path: "/path/to/vindrcxr/embeddings"
  img_extension: ""
  input_type: "global"

mimic:
  images_path: "/path/to/mimic/images"
  train_list: "mimic-cxr-2.0.0-train.csv"
  disease_embedding_path: "/path/to/mimic/embeddings"
  img_extension: ""
  input_type: "global"

rsna:
  images_path: "/path/to/rsna/images"
  train_list: "RSNAPneumonia_train.txt"
  disease_embedding_path: "/path/to/rsna/embeddings"
  img_extension: ""
  input_type: "global"

vindrcxr_local:
  images_path: "/path/to/vindrcxr/patches"
  train_list: "VinDR_cxr_localization_diseased_patches.txt"
  disease_embedding_path: "/path/to/vindrcxr/patches_embeddings"
  img_extension: ".jpeg"
  input_type: "local"

chestxdet_local:
  images_path: "/path/to/chestxdet/patches"
  train_list: "ChestX-Det_all_patches.txt"
  disease_embedding_path: "/path/to/chestxdet/patches_embeddings"
  img_extension: ".png"
  input_type: "local"

tbx11k_local:
  images_path: "/path/to/tbx11k/patches"
  train_list: "TBX11K_all_patches.txt"
  disease_embedding_path: "/path/to/tbx11k/patches_embeddings"
  img_extension: ".png"
  input_type: "local"

node21_local:
  images_path: "/path/to/node21/patches"
  train_list: "Node21_all_patches_3x.txt"
  disease_embedding_path: "/path/to/node21/patches_embeddings"
  img_extension: ".png"
  input_type: "local"

chestxdet_global:
  images_path: "/path/to/chestxdet/train"
  train_list: "ChestX-Det_all_patches.txt"
  disease_embedding_path: "/path/to/chestxdet/embeddings"
  img_extension: ".png"
  input_type: "global"

tbx11k_global:
  images_path: "/path/to/tbx11k/imgs"
  train_list: "TBX11K_all_patches.txt"
  disease_embedding_path: "/path/to/tbx11k/TBX11K_embeddings"
  img_extension: ".png"
  input_type: "global"

node21_global:
  images_path: "/path/to/node21/images"
  train_list: "Node21_all_patches_3x.txt"
  disease_embedding_path: "/path/to/node21/embeddings"
  img_extension: ".png"
  input_type: "global"
